#+TITLE:   Shekhar Mittal
#+AUTHOR:    Shekhar Mittal
#+EMAIL:     shekhar.mittal@gmail.com
#+DESCRIPTION: Shekhar's personal website
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil creator:nil postamble:nil
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Belleza' rel='stylesheet' type='text/css'>
#+STYLE: <LINK href="css/stylesheet.css" rel="stylesheet" type="text/css">
#+STYLE: <script src="javascripts/jquery.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.hashchange.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.easytabs.js" type="text/javascript"></script>  
#+STYLE: <script type="text/javascript"> $(document).ready(function(){ $('#tab-container').easytabs();});</script>
# End:

#+BEGIN_HTML
<div id="tab-container">
  <ul>
    <li><a href="#outline-container-1">About</a></li>
    <li><a href="#outline-container-2">Research</a></li>
    <li><a href="#outline-container-3">Papers</a></li>
    <li><a href="#outline-container-4">Tools</a></li>
    <li><a href="#outline-container-5">Hacks</a></li>
  </ul>
#+END_HTML


-----
* About
I am a Master of Public Policy student in [[harrisschool.uchicago.edu][Harris School of Public Policy]] at [[http://www.uchicago.edu/index.shtml][University of Chicago]], Chicago. My expected graduation date is June 2013. I have been working with [[http://www.chicagobooth.edu/faculty/bio.aspx%3Fperson_id%3D12824551424][Professor Marianne Bertrand]] at Booth Graduate School of Business since April, 2012. I have also been working with [[http://harrisschool.uchicago.edu/directory/faculty/b-pablo_montagnes][Professor Pablo Montagnes]] at Harris School of Public Policy since January, 2012. 

I am interested in poverty and development issues in emerging economies. Specifically, I am interested in understanding how the incentives of various stakeholders such as politicians, bureaucrats, and citizens vary and need to be consider this variation towards achieving intended policy outcomes.

I am from India. I received an undergraduate degree in Computer Engineering from University of Delhi. I started my career with Cisco Systems as a Software Engineer in their Core Routing Business Unit. It did not take me long to realise that life of a full time software engineer will not be fulfilling. My first move was to a [[http://praja.in][start-up]] which was interested in urban development issues. This was eventually followed by a stint at a public policy think-tank - [[http://schoolchoice.in][Center for Civil Society]]. Here I primarily looked at elementary education sector in India with a specific focus on school choice and the then recently legislated Right of Children to Free and Compulsory Education Act, 2009. 

-----
I am available at shekhar.at.uchicago.dot.edu and shekhar.dot.mittal.at.gmail.dot.com. My resume last updated on October 14, 2012 can be found [[http://shekhar.me/resume/resume.pdf][here]]. My linkedin profile can be found [[http://www.linkedin.com/in/shekharmittal][here]]. From time to time I become active on [[http://twitter.com/shekhar_m][twitter]]. 
* Research
Marianne Bertrand

Pablo Montagnes
-----
* Papers
Whats in a name

Independent Study

Viewpoint

Criminals Beget Criminals Effect

-----
* Tools
I don't claim to be a computer science nerd but from time to time I wonder if there was a tool to help me do the task that I was performing better. This page is for people like me, on this page I list some tools that I have used and found useful and fascinating. All of them are free and have an active online community. They made my work efficient and fun. In case you think I should add something to this list, I am always up for trying new useful tools. (Disclaimer: In some cases I would not have latched on to them had it not been for my computer sciency geeky friends) 

*** [[http://drupal.org/][Drupal]]


*** [[http://code.google.com/p/google-refine/][Google Refine]]

*** [[http://www.frontlinesms.com/][FrontlineSMS]]

*** [[http://www.ushahidi.com][Ushahidi]]

*** [[http://www.gnu.org/software/emacs/][Emacs]]

*** [[http://orgmode.org/][Org-Mode]]
    ----- 
* Scripts and Hacks

*** Perl Script

*** Stata Scripts
-----
