#+TITLE:   Shekhar Mittal
#+AUTHOR:    Shekhar Mittal
#+EMAIL:     shekhar.mittal@gmail.com
#+DESCRIPTION: Shekhar's personal website
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil creator:nil postamble:nil
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Belleza' rel='stylesheet' type='text/css'>
#+STYLE: <LINK href="css/stylesheet.css" rel="stylesheet" type="text/css">
#+STYLE: <script src="javascripts/jquery.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.hashchange.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.easytabs.js" type="text/javascript"></script>  
#+STYLE: <script type="text/javascript"> $(document).ready(function(){ $('#tab-container').easytabs();});</script>
# End:

#+BEGIN_HTML
<div id="tab-container">
  <ul>
    <li><a href="#outline-container-1">About</a></li>
    <li><a href="#outline-container-2">Research</a></li>
    <li><a href="#outline-container-3">Papers</a></li>
    <li><a href="#outline-container-4">Tools</a></li>
    <li><a href="#outline-container-5">Scripts</a></li>
    <a href="./resume/resume.pdf">Resume</a>
  </ul>
#+END_HTML
-----
* About
I am a Master of Public Policy student at [[http://harrisschool.uchicago.edu/][Harris School of Public Policy]] at [[http://www.uchicago.edu/index.shtml][University of Chicago]]. My expected graduation date is June 2013. I have been working under [[http://faculty.chicagobooth.edu/marianne.bertrand/index.html][Professor Marianne Bertrand]] at Booth Graduate School of Business since April, 2012. I have also been a graduate research assistant for [[http://harrisschool.uchicago.edu/directory/faculty/b-pablo_montagnes][Professor Pablo Montagnes]] at Harris School of Public Policy since January, 2012. 

I am interested in poverty and development issues in emerging economies. Specifically, I want to understand how the incentives of various stakeholders such as politicians, bureaucrats, and citizens vary. I also want to analyze the impact of this variation towards achieving intended developmental outcomes.

I received an undergraduate degree in Computer Engineering from University of Delhi. I started my career with Cisco Systems as a software developer in their Core Routing Business Unit. I then moved to a [[http://praja.in][start-up]] which was interested in urban development issues. Most of my time here was spent on building our online platform and collaborating with citizen groups who could potentially use the platform. I followed it with a stint at a public policy think-tank - [[http://schoolchoice.in][Center for Civil Society]]. At CCS, I focussed on the elementary education sector with an emphasis on school choice and the then recently legislated Right of Children to Free and Compulsory Education Act, 2009. 

-----
I am available at shekhar.at.uchicago.dot.edu and shekhar.dot.mittal.at.gmail.dot.com. My resume last updated on October 21, 2012 can be found [[http://shekhar.me/resume/resume.pdf][here]]. My linkedin profile can be found [[http://www.linkedin.com/in/shekharmittal][here]]. Occasionally, I am active on [[http://twitter.com/shekhar_m][twitter]]. 
* Research
*** Measuring performance and analysing time-use of Indian Administrative Service (IAS) officers
I am involved in this project under Professor Marianne Bertrand and [[http://dss.ucsd.edu/~pniehaus/][Professor Paul Niehaus]]. \\

Currently, I am looking at how public grievance systems in various states of India can be used to measure the effectiveness of district level IAS officers.

I undertook a ﬁeld trip to Bihar, India to understand the time-use of district magistrates. Here, I shadowed 2 district magistrates for a week each for as much time as they permitted. The goal of the exercise was multi-fold: to grasp the variation in the tasks that a district magistrate undertakes, to understand the dynamics of her relationship with all the agents she interacts with, the constraints in which she is expected to deliver, and her role and responsibilities. Another aim of the exercise was to understand the organisational setup at the state/district/sub-district level.  

I developed time-use tracking forms and survey questionnaires for the district magistrates, formulated Right to Information Act questionnaires to get data which could help measure the performance of district level IAS oﬃcers as part of their statutory & regulatory responsibilities.

In the initial stages, I reviewed government documents to understand the statutory and developmental responsibilities of IAS oﬃcers and narrowed the research problem. Between all this, I wrote perl scripts to get election data for national and state level elections (1980 onwards) in India.


*** Effect of name order in Senate roll call voting pattern
Under Professor Pablo Montagnes, I am analysing the impact of the order in which a senator is called to vote on her voting behavior. We are able to do this because Senators in the US are called to vote in the order of their last names. \\

Using combined fixed effects at the senator level and at the congress level, we show that the agreement level of the senators with their party goes up as we go down the order. The major magnitude of the result is being driven by party unity. Senators also get signal from
the way in which senators from her party have already voted (bandwagon effect).

Besides doing the stata analysis, I also wrote perl scripts to extract senate and house roll-call data from 1940 into an analysable data set.

-----
* Papers
Short working paper: [[http://shekhar.me/papers/distance.pdf][“Distance as an instrument for measuring centralized control in government schools”]], Shekhar Mittal, December 2012.\\

Research design as part of course-work: [[http://shekhar.me/papers/pe_researchdesign.pdf]["Indian Politics: The Criminals beget Criminals Effect"]], May 2012.\\

Policy memo: [[http://shekhar.me/papers/viewpoint10.pdf][“Reservation in Private Schools under the Right to Education Act: Model for Implementation”]], Shekhar Mittal and Parth J Shah, December 2010.\\

-----
* Tools
I don't claim to be a computer science nerd but from time to time I wonder if there was a better way to do the task that I was performing. This page is for people like me. Here, I list tools that I have used, and found useful and fascinating. All of them are free and have an active online community. They made my work efficient and fun. If you think I should add something to this list, I am always up for trying new useful tools. (Disclaimer: In some cases, I would not have latched on to these tools had it not been for my computer sciency geeky friends.) 

*** Drupal ([[http://drupal.org/][Link]])
If you are looking to create a website which goes beyond text/html/css requirements, drupal is it. A lot of times one needs to include functionalities which are complicated but fairly common. Think integrating google maps, blogs, forums, wikis, anything and everything into one website. Chances are that you will find a module in Drupal which suits your needs closely.

*** Google Refine ([[http://code.google.com/p/google-refine/][Link]])
If you look into government data developing countries, chances are you regularly come across data with spelling and naming inconsistencies. Google Refine helps you solve that problem. There are other ways in which people have gotten around this problem (reclink command in stata, Prof Bhavnani wrote an [[http://www.rikhilbhavnani.com/RB-AMIN.exe%20documentation.pdf][application]]). I have not tried those other ways. Besides, this one has the google name behind it.

*** FrontlineSMS ([[http://www.frontlinesms.com/][Link]])
There are lot of SMS server offerings out there. One has to pay for them and be sure of what she wants. On top of that, those services usually require you to have access to internet - a luxury not easily available in developing countries. FrontlineSMS allows you to create and manage common SMS activities such as making announcements, conducting polls and sending automatic replies to incoming SMS. Potentially, a great tool to collect data from the field. All one needs is a laptop and a mobile phone. 

*** Ushahidi ([[http://www.ushahidi.com][Link]])
Crowdsourcing is going to be the way to collect data in the near future. Think many kind of issues ([[http://votereport.pk/][election violations]], [[http://www.prijavikorupcija.org/][transparency]], etc.)  getting reported live and coming up on a map in a crowd sourced manner. Ushahidi will enable that. 

*** Emacs ([[http://www.gnu.org/software/emacs/][Link]]) plus Org-Mode ([[http://orgmode.org/][Link]])
These tools have a little steep learning curve but once you cross it, they are addictive! I use emacs to write and edit: assignments, papers, presentations, latex files, scripts, anything and everything. One can open multiple files in the same window and then compile them from there itself. 
Mouse becomes redundant. Org-mode allows you to create to-do lists, track agendas, create text files and then very easily export them to other formats such as latex, pdfs and htmls. 

This website was completely built in emacs and org-mode. 

----- 
* Scripts 
Here you will find a few basic scripts that I put together (copied and modified from internet) to clean data that was needed in our research. Feel free to use them. Send some more my way if you have them.  
Most scripts that we write have already been written by someone. No point in reinventing the wheel. Hopefully this list will grow with time. 

*** Perl Scripts
a. Convert from pdf to text ([[http://shekhar.me/scripts/createpdf2txt.pl][Download]])\\
Copying text from pdf is easy. But if one has to do it for multiple files and multiple pages it can be slow, painful and boring. This small script automates it. \\

b. Convert from text to csv ([[http://shekhar.me/scripts/createtxt2csv.pl][Download]])\\
One needs to know how to handle [[perldoc.perl.org/perlre.html][regular expressions]] in perl to do this (if one wants to use this code, she will have to change the regular expression for sure). This script reads the text file line by line and puts the content in the required csv format. \\

*** Stata Scripts 
Writing "for loops" in stata is cumbersome. Here ([[http://shekhar.me/scripts/multiplesheets2singledataset.do][download]]) is a stata file in which I read specific cells from the multiple tabs of the same excel file and then append them into a single dataset. 
-----
