#+TITLE:   Shekhar Mittal
#+AUTHOR:    Shekhar Mittal
#+EMAIL:     shekhar.mittal@gmail.com
#+DESCRIPTION: Shekhar's personal website
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil creator:nil postamble:nil
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
#+STYLE:<link href='http://fonts.googleapis.com/css?family=Belleza' rel='stylesheet' type='text/css'>
#+STYLE: <LINK href="css/stylesheet.css" rel="stylesheet" type="text/css">
#+STYLE: <script src="javascripts/jquery.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.hashchange.js" type="text/javascript"></script>
#+STYLE: <script src="javascripts/jquery.easytabs.js" type="text/javascript"></script>  
#+STYLE: <script type="text/javascript"> $(document).ready(function(){ $('#tab-container').easytabs();});</script>
# End:

#+BEGIN_HTML
<div id="tab-container">
  <ul>
    <li><a href="#outline-container-1">About</a></li>
    <li><a href="#outline-container-2">Research</a></li>
    <li><a href="#outline-container-3">Papers</a></li>
    <li><a href="#outline-container-4">Tools</a></li>
    <li><a href="#outline-container-5">Hacks</a></li>
  </ul>
#+END_HTML


-----
* About
I am a Master of Public Policy student in [[http://harrisschool.uchicago.edu/][Harris School of Public Policy]] at [[http://www.uchicago.edu/index.shtml][University of Chicago]], Chicago. My expected graduation date is June 2013. I have been working with [[http://faculty.chicagobooth.edu/marianne.bertrand/index.html][Professor Marianne Bertrand]] at Booth Graduate School of Business since April, 2012. I have also been working with [[http://harrisschool.uchicago.edu/directory/faculty/b-pablo_montagnes][Professor Pablo Montagnes]] at Harris School of Public Policy since January, 2012. 

I am interested in poverty and development issues in emerging economies. Specifically, I am interested in understanding how the incentives of various stakeholders such as politicians, bureaucrats, and citizens vary and we need to consider this variation towards achieving intended developmental outcomes.

I am from India. I received an undergraduate degree in Computer Engineering from University of Delhi. I started my career with Cisco Systems as a Software Engineer in their Core Routing Business Unit. It did not take me long to realise that life of a full time software engineer will not be fulfilling. My first move was to a [[http://praja.in][start-up]] which was interested in urban development issues. This was followed by a stint at a public policy think-tank - [[http://schoolchoice.in][Center for Civil Society]]. At CCS, I looked at elementary education sector in India with a specific focus on school choice and the then recently legislated Right of Children to Free and Compulsory Education Act, 2009. 

-----
I am available at shekhar.at.uchicago.dot.edu and shekhar.dot.mittal.at.gmail.dot.com. My resume last updated on October 14, 2012 can be found [[http://shekhar.me/resume/resume.pdf][here]]. My linkedin profile can be found [[http://www.linkedin.com/in/shekharmittal][here]]. From time to time I become active on [[http://twitter.com/shekhar_m][twitter]]. 
* Research
Marianne Bertrand

Pablo Montagnes
-----
* Papers
Whats in a name

Independent Study

Viewpoint

Criminals Beget Criminals Effect

-----
* Tools
I don't claim to be a computer science nerd but from time to time I wonder if there was a tool to help me do the task that I was performing better. This page is for people like me. Here, I list some tools that I have used, and found useful and fascinating. All of them are free and have an active online community. They make my work efficient and fun. In case you think I should add something to this list, I am always up for trying new useful tools. (Disclaimer: In some cases, I would not have latched on to these tools  had it not been for my computer sciency geeky friends.) 

*** [[http://drupal.org/][Drupal]]
If you are looking to create a website which goes beyond your typical texty/html/css requirements, drupal is it. A lot of the times one needs to include functionalities which are complicated but fairly common. Think integrating google maps, blogs, forums, wikis, anything and everything into one website. Chances are that you will find a module in Drupal which suits your needs closely.

*** [[http://code.google.com/p/google-refine/][Google Refine]]
If you are the types who looks into government data especially in developing countries such as India, you regularly come across data with spelling and naming inconsistencies. This is great tool that helps you solve that problem. I am told there are other ways in which people have gotten around this problem (reclink command in stata, Prof Bhavnani wrote an [[http://www.rikhilbhavnani.com/RB-AMIN.exe%20documentation.pdf][application]]) but this one has the google name behind it.

*** [[http://www.frontlinesms.com/][FrontlineSMS]]
There are lot of SMS server offerings out there, one has to obviously pay for them and be sure of what he/she wants. On top of that, those services usually require you to have access to internet - a luxury not easily available in developing countries. FrontlineSMS is a tool that allows you to create and manage common SMS activities such as making announcements, conducting polls and sending automatic replies to incoming SMS. Potentially a great tool to collect data from the field. All one needs is a laptop and a mobile phone. 

*** [[http://www.ushahidi.com][Ushahidi]]
A part of me feels that crowdsourcing is going to be the way to collect data in the near future. Think any kind of issues ([[http://votereport.pk/][election violations]], [[http://www.prijavikorupcija.org/][transparency]], etc.)  getting reported live and coming up on a map and all of that in a crowd sourced manner. Ushahidi will be at the forefront of enabling that. 

*** [[http://www.gnu.org/software/emacs/][Emacs]] plus [[http://orgmode.org/][Org-Mode]]
These tools have a little steep learning curve but once you cross it, they are addictive! I use emacs to write and edit: assignments, papers, presentations, latex files, scripts, anything and everything. One can open multiple files in the same window and then compile them from there itself. 
Mouse becomes redundant. Org-mode allows you to create to-do lists, track agendas, create text files and then very easily export them to other formats such as latex, pdfs and htmls. 

This website was completely built in emacs and org-mode. 

    ----- 
* Scripts and Hacks
This page has a few basic scripts that I put together (from internet) to clean data that was needed in our research. Feel free to use them, send some my way (I don't like to reinvent the wheel) if you have them.  
Most scripts that we end up writing have already been written by someone at someplace. This is my way of giving back. 

*** Perl Scripts
**** 

*** Stata Scripts
-----
