#+TITLE:     
#+AUTHOR:    
#+EMAIL:     
#+DATE:      
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+latex_class: article
#+latex_header: \usepackage[left=2cm,top=1.8cm,right=2cm,bottom=2cm,nohead,nofoot]{geometry}
#+latex_header: \usepackage{bbding}
#+latex_header: \usepackage{multicol}
#+latex_header: \usepackage{eurosym}
#+latex_header: \usepackage{color,graphicx}
#+latex_header: \usepackage[usenames,dvipsnames]{xcolor}
#+latex_header: \usepackage[small,compact]{titlesec}
#+latex_header: \usepackage{fontspec,xltxtra,xunicode}
#+latex_header: \setromanfont[Mapping=tex-text]{Linux Libertine O}
#+latex_header: \setsansfont[Scale=MatchLowercase,Mapping=tex-text]{Linux Libertine O}
#+latex_header: \setmonofont[Scale=MatchLowercase]{MgOpen Modata}
#+latex_header: \usepackage{hyperref}
#+latex_header: \definecolor{linkcolour}{rgb}{0,0,0.6}
#+latex_header: \hypersetup{colorlinks,breaklinks,urlcolor=linkcolour, linkcolor=linkcolour}
#+latex_header: \pagestyle{empty}
#+latex_header: \usepackage{enumitem}
#+latex_header: \setitemize[0]{leftmargin=*,itemsep=0pt,parsep=1pt,topsep=1pt}

#+begin_latex
\begin{centering} \par{
		{\sffamily\huge Shekhar Mittal}\\
\vspace{1em}
{\normalsize 110 Westwood Plaza, C-525 Entrepreneurs Hall Los Angeles, CA - 90095-1481, USA\\
{\Phone} 734-780-1120   {\Envelope} \href{mailto:shekhar.mittal.2017@anderson.ucla.edu}{shekhar.mittal.2017@anderson.ucla.edu}  {\HandRight} \href{http://shekharmittal.info}{http://shekharmittal.info}\\}}
\end{centering}

\titleformat{\section}
	{\scshape\Large\raggedright}{}{0em}{}[\color{black}\titlerule]
\titleformat{\subsection}
	{\large\raggedright}{}{0em}{}[\color{black}]
\titlespacing{\section}{0pt}{2pt}{3pt}
\renewcommand{\labelitemi}{$\bullet$}

#+end_latex
* Education
\flushleft
University of California, Los Angeles, \textbf{Anderson School of Management} \hfill \textsc{\normalsize September 2013 -- Current}\\
Ph.D., Global Economics and Management\\
Areas of Interest: Political Economy, Development, India.\\
\vspace{1em}
University of Chicago, \textbf{Harris School of Public Policy} \hfill \textsc{\normalsize September 2011 -- June 2013}\\
Awards: Dean's Scholarship (2011-2013), J.N. Tata Scholar (2011), K.C. Mahindra Scholar (2011)\\
\vspace{1em}
Delhi University, \textbf{Delhi College of Engineering}, New Delhi, India \hfill \textsc{\normalsize August 2003 -- June 2007}\\ 
Bachelor of Engineering in \emph{Computer Engineering}, \emph{First Division}\\
* Research
** *\emph{Ongoing}*
\flushleft
\emph{Improving public service performance via electoral channels}, \hfill \textsc{\normalsize March 2015 onwards}\\
with Professor Aprajit Mahajan\\
\vspace{0.5em}
\emph{Caste, gender bias and dowry} \hfill \textsc{\normalsize Summer 2015 onwards}\\
with Professor Paola Giuliano\\
\vspace{0.5em}
Graduate Research Assistant to Professor Romain Wacziarg \hfill
\textsc{\normalsize Summer 2013, Summer 2015}\\
[[http://www.anderson.ucla.edu/faculty/global-economics-and-management/phd-program][Anderson School of Management]], University of California, Los Angeles \\
\emph{Cultural distances using World Values Survey}
- Developed multiple indices to measure cultural distance across countries, using the World Values Survey data. 
- Measured the correlation between cultural and genetic distance across countries.
\vspace{0.5em}
Graduate Research Assistant to Professor Paola Giuliano \hfill
\textsc{\normalsize Summer 2015}\\
[[http://www.anderson.ucla.edu/faculty/global-economics-and-management/phd-program][Anderson School of Management]], University of California, Los Angeles \\
\emph{United States Historical Election Returns}
- Calculated county level vote shares of all political parties from 1824 to 1968.
\vspace{0.5em}

** *\emph{Past Experience}*
\flushleft
Graduate Research Assistant to Professor Edward Leamer \hfill
\textsc{\normalsize July 2013 -- September 2013}\\
[[http://www.anderson.ucla.edu/faculty/global-economics-and-management/phd-program][Anderson School of Management]], University of California, Los Angeles \\
\emph{Estimated extreme coefficients of $2^k$ regressions}
- Implemented possible methods to efficiently determine extreme coefficients of $2^k$ regressions.
- Developed efficient techniques to identify all the orthants of $2^k$ regression coefficients. 
\vspace{0.5em}
Graduate Research Assistant to Professor Marianne Bertrand \hfill
\textsc{\normalsize April 2012 -- June 2013}\\
[[http://www.chicagobooth.edu/faculty/bio.aspx?person_id%3D12824551424][Booth School of Business]], University of Chicago \\
\emph{Evaluation of Right to Public Service Schemes}
- Travelled to Karnataka to understand the design and implementation of the Right to Public Services Act. Interacted with all the government level stakeholders and visited various government offices.
- Developed and piloted a survey questionnaire which captured the experience and perception of citizens who availed the services that are covered under the Act.
- Undertook a field trip to Bihar, India to understand the time-use of district magistrates and to understand the bureaucratic setup at the district level.
\vspace{0.5em}
\pagebreak
Graduate Research Assistant to Professor Pablo Montagnes \hfill
\textsc{April 2012 -- December 2012}\\
[[http://harrisschool.uchicago.edu/directory/faculty/b-pablo_montagnes][Harris School of Public Policy]], University of Chicago \\ 
\emph{Effect of name order in senate roll call voting pattern.}
 - Using combined fixed effects at the senator level and at the
   congress level, evaluated the impact of alphabetical order of the
   senators' last names on Senate roll call. 
 - Wrote Perl scripts to extract senate and house roll-call data starting from 1940 into a analysable data set.
\vspace{0.5em}
Graduate Research Assistant to Professor Pablo Montagnes \hfill
\textsc{January 2012 -- March 2012}\\
[[http://harrisschool.uchicago.edu/directory/faculty/b-pablo_montagnes][Harris School of Public Policy]], University of Chicago \\ 
\emph{Understanding voting patterns for simultaneous elections in a given year at the precinct level}
- Designed a Stata program that extracts information from the Cook
  County precinct level election results into a user-friendly data
  set.
- Wrote Stata programs to clean and analyze data.
\vspace{0.5em}
Graduate Research Assistant to A. Rupa Datta, Vice President and
Senior Fellow  \hfill \textsc{October 2011 -- March 2012}\\
[[http://www.norc.org/Research/Projects/Pages/national-survey-of-early-care-and-education.aspx][National Opinion Research Centre]] at the University of Chicago \\ 
\emph{National Survey of Early Care and Education}
- Managed the IRB approval process for all the school districts
  from which the survey intended to interview early care providers.

* Writing
- \emph{Summer Paper:} ``Mumbai municipal elections: Performance 
  and incumbency effect analysis", Summer 2014.

- \emph{Short Paper:} ``Distance as an instrument for measuring
  centralized control in government schools'', December 2012.

  \emph{Summary:} The paper shows that the quality and outcomes of a
  government school deteriorate as the distance of a government school
  from district headquarters increases. This effect is absent in
  private schools which tend to be decentralized.

- \emph{Research Design as part of course-work:} ``Indian Politics: The
  Criminals beget Criminals Effect", May 2012.
 
  \emph{Summary:} I create a research design that uses regression
  discontinuity design to prove that when the incumbent in Indian
  elections is a criminal, and the opposition party thinks that there
  is a high probability of the election being close, the opposition
  party also tends to nominate a criminal.
  [[http://shekharmittal.info/papers/pe_researchdesign.pdf][Link]] 


- \emph{Policy Memo:} ``Reservation in Private Schools under the Right
  to Education Act: Model for Implementation'', Shekhar Mittal and
  Parth J Shah, December 2010.

  \emph{Summary:} The memo suggests a model for effective
  implementation of a specific provision under the Right of Children
  to Free and Compulsory Education Act, 2009. [[http://shekharmittal.info/papers/viewpoint10.pdf][Link]]

* Teaching
*UCLA Anderson*: Teaching Assistant - Managerial Economics (MBA, 2014-2015)

* Professional Experience
\flushleft
*Senior Campaign Associate*, /[[http://ccs.in][Centre for Civil Society]]/, New Delhi,
India \hfill \textsc{\normalsize July 2010 -- June 2011}\\
\vspace{0.6em}
*Program Manager and Platform Engineer*, /[[http://praja.in][Praja]]/, Bangalore, India
 \hfill \textsc{\normalsize August 2009 -- June 2010}\\
\vspace{0.6em}
*Software Engineer*, /[[http://www.cisco.com][Cisco Systems]]/, Bangalore, India \hfill \textsc{\normalsize July 2007 -- July 2009}\\

* Skills
*Highly Proficient*: Stata, Drupal, C, Emacs, Linux (Ubuntu) \\
*Proficient*: Matlab, MySQL, R, Perl \\
*Experienced*: Latex, Python, HTML, CSS \\
\pagebreak
* Personal
*Citizenship*: Indian \\
*Languages*: Hindi (native), English (highly proficient)\\
* References
\vspace{-0.2in}
#+latex: \begin{multicols}{2}
- *Romain Wacziarg, Professor of Economics* \\
  Anderson School of Management, UCLA \\ 
  110 Westwood Plaza,o C-510 Entrepreneurs Hall\\ 
  Los Angeles, CA - 90095-1481\\
  [[mailto:wacziarg@ucla.edu][wacziarg@ucla.edu]]\\
- *Paola Giuliano, Assistant Professor of Economics* \\
  Anderson School of Management, UCLA \\ 
  110 Westwood Plaza, C-517 Entrepreneurs Hall\\ 
  Los Angeles, CA - 90095-1481\\
  [[mailto:paola.giuliano@anderson.ucla.edu][paola.giuliano@anderson.ucla.edu]]\\
- *Aprajit Mahajan, Associate Professor* \\
  Dept. of ARE, UC Berkeley \\
  219 Giannini Hall\\
  Berkeley, CA 94720-3310\\
  [[mailto:aprajit@gmail.com][aprajit@gmail.com]]\\
- *Miriam Golden, Professor of Political Science*\\
  UC Los Angeles \\
  3262 Bunche Hall\\
  Los Angeles, CA - 90095-1481\\
  [[mailto:golden@ucla.edu][golden@ucla.edu]]
#+latex: \end{multicols}

